services:
  - type: web
    name: mnist-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 03_server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
